/**
 * Emoji mapping for toppings — used by the tweet composer.
 * Specific topping names take priority, then class fallback.
 */

const TOPPING_EMOJIS: Record<string, string> = {
  // Crust
  "Thin Crust": "🍕",
  "Thick Crust": "🍕",
  "Moon Crust": "🌙",
  "White Bread Crust": "🍞",
  "Gluten Free Crust": "🍕",
  // Sauce
  "Tomato Sauce": "🍅",
  "BBQ Sauce": "🍖",
  "Hazelnut Spread": "🫘",
  "Prismatic Fluid": "🌈",
  // Cheese
  "Mozzarella": "🧀",
  "Smoked Mozzarella": "🧀",
  "Feta": "🧀",
  "Quattro Formaggi": "🧀",
  "Gruyere": "🧀",
  "Vegan Cheese": "🌱",
  "Smoked Gouda": "🧀",
  "Goat Cheese": "🐐",
  "Burnt Cheese": "🔥",
  "Paneer Tikka": "🧀",
  "Provolone": "🧀",
  "Tvaruzek": "🧀",
  "Korbacik": "🧀",
  "Whiz": "🧀",
  "Fried Cheese": "🧀",
  // Meat
  "Pepperoni": "🔴",
  "Salami": "🥓",
  "Turkey Sausage": "🌭",
  "Turkey": "🦃",
  "Smoked Turkey": "🦃",
  "Prosciutto": "🥩",
  "Butter Chicken": "🍗",
  "Ground Beef": "🥩",
  "BBQ Chicken": "🍗",
  "Bacon": "🥓",
  "Meatball": "🧆",
  "Buffalo Chicken": "🍗",
  "Char Siu Pork": "🐷",
  "Cheeseburger": "🍔",
  "Eyeball": "👁️",
  "Finger": "🖐️",
  "Bat": "🦇",
  "Escargot": "🐌",
  "Roast Beef": "🥩",
  "Owl": "🦉",
  "Frog Legs": "🐸",
  "Bologna": "🥪",
  "Dragon Meat": "🐉",
  "Jerk Chicken": "🍗",
  "Oxtail": "🐂",
  "Hot Dog": "🌭",
  "Unicorn": "🦄",
  "Butt": "🍑",
  "Brain": "🧠",
  "Ham": "🍖",
  "Duck": "🦆",
  "Fried Chicken": "🍗",
  "Chicken": "🍗",
  "Chorizo": "🌭",
  "Corn Dog": "🌭",
  "Vegan Sausage": "🌱",
  "Endangered Species": "🦏",
  // Fruit
  "Tomato": "🍅",
  "Psychedelic Tomato": "🍅",
  "Mango": "🥭",
  "Fig": "🫐",
  "Pitaya": "🐉",
  "Lime": "🍋",
  "Blueberry": "🫐",
  "Avocado": "🥑",
  "Green Olive": "🫒",
  "Black Olive": "🫒",
  "Pineapple": "🍍",
  "Durian": "🤢",
  "Banana": "🍌",
  "Grape": "🍇",
  "Strawberry": "🍓",
  "Apple": "🍎",
  "Cherry": "🍒",
  "Blackberry": "🫐",
  "Date": "🌴",
  "Eggplant": "🍆",
  "Orange": "🍊",
  "Grapefruit": "🍊",
  "Peach": "🍑",
  "Cantaloupe": "🍈",
  "Passion Fruit": "💜",
  "Orange Peel": "🍊",
  "Kiwi": "🥝",
  "Watermelon": "🍉",
  "Plantains": "🍌",
  "Lemon": "🍋",
  // Pepper
  "Chili Pepper": "🌶️",
  "Jalapeno Pepper": "🌶️",
  "Shishito Pepper": "🌶️",
  "Banana Pepper": "🌶️",
  "Red Pepper": "🫑",
  "Yellow Pepper": "🫑",
  "Green Pepper": "🫑",
  "Habanero Pepper": "🔥",
  // Fungi
  "Mushroom": "🍄",
  "Black Truffle": "🖤",
  "Magic Mushroom": "🍄",
  "Porcini": "🍄",
  "White Truffle": "🤍",
  "Morel": "🍄",
  "Amanita": "🍄",
  // Nuts
  "Pistachio": "🥜",
  "Peanut": "🥜",
  "Pine Nut": "🌲",
  // Seafood
  "Shrimp": "🦐",
  "Anchovies": "🐟",
  "Lobster": "🦞",
  "Scallop": "🐚",
  "Salmon": "🐟",
  "Sardine": "🐟",
  "Mermaid": "🧜",
  "Pearl": "💎",
  "Cthulhu": "🦑",
  "Hawaiian Poke": "🐟",
  "Octopus": "🐙",
  "Oyster": "🦪",
  "Sea Urchin": "🦔",
  "Sushi": "🍣",
  "Tropical Fish": "🐠",
  "Takoyaki": "🐙",
  "Squid": "🦑",
  // Bugs
  "Cockroach": "🪳",
  "Cricket": "🦗",
  "Worm": "🪱",
  "Yellowjacket": "🐝",
  "Cicada": "🦗",
  "Maggots": "🪱",
  "Spider": "🕷️",
  "Flies": "🪰",
  "Ants": "🐜",
  "Lady Bug": "🐞",
  "Lantern Fly": "🪰",
  // Flowers
  "Hibiscus": "🌺",
  "Dandelion": "🌼",
  "Squash Blossom": "🌻",
  "Wild Dagga": "🌺",
  "Rose": "🌹",
  "Tulip": "🌷",
  "Camellia": "🌸",
  // Herbs & Spices
  "Cannabis": "🌿",
  "Basil": "🌿",
  "Hemp": "🌿",
  "Rosemary": "🌿",
  "Cilantro": "🌿",
  "Parsley": "🌿",
  "Oregano": "🌿",
  "Mint Leaf": "🍃",
  "Hot Pepper Flakes": "🌶️",
  "Bird Seed": "🐦",
  // Eggs
  "Dino Egg": "🦕",
  "Goose Egg": "🥚",
  "Ostrich Egg": "🥚",
  "Hardboiled Egg": "🥚",
  "Feather": "🪶",
  // Space
  "Flag": "🏁",
  "Black Hole": "🕳️",
  "Stardust": "✨",
  "Dream Drops": "💫",
  "Sputnik": "🛸",
  "Robot": "🤖",
  "Tesla": "⚡",
  "Meteorite": "☄️",
  "Alien": "👽",
  "NASA": "🚀",
  "UFO": "🛸",
  "Laika": "🐕",
  // Vegetable
  "Garlic": "🧄",
  "Red Onion": "🧅",
  "White Onion": "🧅",
  "Spinach": "🥬",
  "Arugula": "🥬",
  "Broccoli": "🥦",
  "Broccolini": "🥦",
  "Corn": "🌽",
  "Artichoke Heart": "💚",
  "Asparagus": "🌿",
  "Sweet Potato": "🍠",
  "Peas": "🟢",
  "Kale": "🥬",
  "Cauliflower": "🥦",
  "Bamboo": "🎋",
  "Cactus": "🌵",
  "Tofu": "🧈",
  "Edamame": "🫛",
  "Kimchi": "🥬",
  "Beans": "🫘",
  "Yuca": "🥔",
  "Potato Chips": "🥔",
  "Seitan": "🍖",
  "Shadow Plant": "🌑",
  "Pickled Beet": "🟣",
  "Corona": "😷",
  // Snacks
  "Snap Rocks": "💥",
  "Fried Onion Ring": "🧅",
  "Star Candy": "⭐",
  "Ice Cream": "🍦",
  "Popcorn": "🍿",
  "Peanut Butter": "🥜",
  "Dotoru Chips": "🌰",
  "Melty": "🫠",
  "Teeth": "🦷",
  "Gumball": "🫧",
  "Waffle": "🧇",
  "Marshmallow": "☁️",
  "Cotton Candy": "🍭",
  "Mongda Chips": "🍘",
  "Ramen Noodle": "🍜",
  "Pretzel": "🥨",
  "Bagel": "🥯",
  "Donut": "🍩",
  "Vada Pav": "🍔",
  "Peanut Chews": "🍫",
  "French Fry": "🍟",
  "Curly Fry": "🍟",
  "Taco": "🌮",
  "Mac and Cheese": "🧀",
  "Alphabet Soup": "🍲",
  "Banh Mi": "🥖",
  "Rice": "🍚",
  "Spaghetti": "🍝",
  "Soup": "🍲",
  "Beer": "🍺",
  "Twinkie Wiener Sandwich": "🌭",
  // Random / Miscellaneous
  "Hair": "💇",
  "Key": "🔑",
  "Eyelash": "👁️",
  "Cigarette": "🚬",
  "Jelly": "🫙",
  "Buttons": "🔘",
  "Glitter": "✨",
  "Cloud": "☁️",
  "Chess": "♟️",
  "Gold Flake": "🏆",
  "Diamonds": "💎",
  "Dog Toy": "🐕",
  "Battery": "🔋",
  "Yarn Ball": "🧶",
  "Tires": "🛞",
  "Butter": "🧈",
  "Hand Sanitizer": "🧴",
  "Rocks": "🪨",
  "Light Bulb": "💡",
  "Polygon": "🔷",
  "Arrow": "➡️",
  "Pill": "💊",
  "Crown": "👑",
  "Glasses": "👓",
  "Lip Balm": "💋",
  "Oil Spill": "🛢️",
  "FOMO": "😰",
  "Pizza Mafia": "🤌",
  "Screw": "🔩",
  "Headphone": "🎧",
  "Sprinkles": "🎉",
  "Christmas Lights": "🎄",
  "Swole Doge": "🐕",
  "Pizza Saver": "🍕",
  "Peptomics": "🧬",
  "Bowtie": "🎀",
  "Puzzle": "🧩",
  "Laszlo": "₿",
  "Book": "📚",
  "Supernatural Poodle": "🐩",
  "Monkey Dome": "🐵",
  "Preamp": "🎸",
  "Transit Token": "🚇",
  "Glue": "🫠",
  "Crayon": "🖍️",
  "3D Glasses": "🥽",
  "Magic Wand": "🪄",
  "Poker Chip": "🎰",
  "Stuffed Animal": "🧸",
  "Heart Beat": "❤️",
  "Computer Chip": "💻",
  "Paracell": "🔮",
  // Drizzle / Sauce extras
  "Mayo": "🥛",
  "Ranch": "🤠",
  "Ketchup": "🟥",
  "Hot Sauce": "🔥",
  "Salsa Verde": "🟢",
  "Hot Honey": "🍯",
  "Sriracha": "🔥",
  "Apple Sauce": "🍎",
};

const CLASS_EMOJIS: Record<string, string> = {
  "Crust": "🍕",
  "Sauce": "🫗",
  "Cheese": "🧀",
  "Meat": "🥩",
  "Fruit": "🍎",
  "Vegetable": "🥬",
  "Pepper": "🌶️",
  "Fungi": "🍄",
  "Nuts": "🥜",
  "Seafood": "🦐",
  "Bugs": "🐛",
  "Flowers": "🌸",
  "Herbs & Spices": "🌿",
  "Eggs": "🥚",
  "Space": "🚀",
  "Snacks": "🍿",
  "Random": "✨",
  "Drizzle": "💧",
};

export function getToppingEmoji(name: string, className?: string): string {
  return TOPPING_EMOJIS[name] || (className ? CLASS_EMOJIS[className] : null) || "🍕";
}
