import type { VercelRequest, VercelResponse } from "@vercel/node";
import { kv } from "@vercel/kv";

interface RecentEntry {
  tokenId: number;
  tweetedAt: string;
}

const KV_KEY = "recently-tweeted";
const THIRTY_DAYS_MS = 30 * 24 * 60 * 60 * 1000;

/**
 * Pre-built list of Rare Pizza token IDs whose owners have X/Twitter
 * linked on OpenSea. Generated by scripts/find-x-owners.mjs.
 * Pick a random entry — no OpenSea calls needed at request time.
 */
const X_LINKED_PIZZAS = [
  { tokenId: 148, twitter: "ernestleedotcom" },
  { tokenId: 151, twitter: "snack_man" },
  { tokenId: 153, twitter: "wuestenigel" },
  { tokenId: 218, twitter: "Joffnft" },
  { tokenId: 226, twitter: "Joffnft" },
  { tokenId: 227, twitter: "beleevens" },
  { tokenId: 304, twitter: "ETHtoad" },
  { tokenId: 389, twitter: "bobcatbts" },
  { tokenId: 419, twitter: "garypalmerjr" },
  { tokenId: 451, twitter: "garypalmerjr" },
  { tokenId: 598, twitter: "EthDoh" },
  { tokenId: 625, twitter: "thomasdylandan2" },
  { tokenId: 645, twitter: "thomasdylandan2" },
  { tokenId: 650, twitter: "sumrtime2" },
  { tokenId: 669, twitter: "RelprimeS" },
  { tokenId: 693, twitter: "ariutokintumi" },
  { tokenId: 842, twitter: "ETHtoad" },
  { tokenId: 865, twitter: "bestfoodalex" },
  { tokenId: 945, twitter: "nef7773" },
  { tokenId: 1053, twitter: "snack_man" },
  { tokenId: 1059, twitter: "andyjreyes" },
  { tokenId: 1060, twitter: "CharredJawa" },
  { tokenId: 1062, twitter: "snack_man" },
  { tokenId: 1063, twitter: "snack_man" },
  { tokenId: 1072, twitter: "garypalmerjr" },
  { tokenId: 1093, twitter: "bitpixi" },
  { tokenId: 1113, twitter: "joelcomm" },
  { tokenId: 1117, twitter: "thomasdylandan2" },
  { tokenId: 1164, twitter: "thomasdylandan2" },
  { tokenId: 1179, twitter: "tomaytravel" },
  { tokenId: 1183, twitter: "thomasdylandan2" },
  { tokenId: 1184, twitter: "soojincho" },
  { tokenId: 1186, twitter: "ainmaia" },
  { tokenId: 1237, twitter: "BardIonson" },
  { tokenId: 1312, twitter: "CMNisal" },
  { tokenId: 1323, twitter: "cryptopherjones" },
  { tokenId: 1391, twitter: "snack_man" },
  { tokenId: 1409, twitter: "ToyBoogers" },
  { tokenId: 1476, twitter: "sreyeMnayR" },
  { tokenId: 1545, twitter: "mrboups" },
  { tokenId: 1552, twitter: "snack_man" },
  { tokenId: 1558, twitter: "snack_man" },
  { tokenId: 1564, twitter: "JENeticsDesign" },
  { tokenId: 1570, twitter: "bestfoodalex" },
  { tokenId: 1574, twitter: "bestfoodalex" },
  { tokenId: 1575, twitter: "bestfoodalex" },
  { tokenId: 1594, twitter: "lindslonadier" },
  { tokenId: 1603, twitter: "MauiMiners" },
  { tokenId: 1636, twitter: "sethakkerman" },
  { tokenId: 1638, twitter: "cielxnoel" },
  { tokenId: 1671, twitter: "0xbagelface" },
  { tokenId: 1686, twitter: "frdysk" },
  { tokenId: 1778, twitter: "punkcastxyz" },
  { tokenId: 1783, twitter: "Ehsanomics" },
  { tokenId: 1788, twitter: "chrismanciero" },
  { tokenId: 1848, twitter: "QuantumVariant" },
  { tokenId: 1863, twitter: "snack_man" },
  { tokenId: 1864, twitter: "snack_man" },
  { tokenId: 1865, twitter: "ProfWerder" },
  { tokenId: 1874, twitter: "ArnoKiss" },
  { tokenId: 1904, twitter: "jayaddamo" },
  { tokenId: 1923, twitter: "snack_man" },
  { tokenId: 2041, twitter: "RagingBitcoin" },
  { tokenId: 2085, twitter: "SaraniR2000" },
  { tokenId: 2095, twitter: "snack_man" },
  { tokenId: 2098, twitter: "Nikhil_Mahana" },
  { tokenId: 2099, twitter: "snack_man" },
  { tokenId: 2103, twitter: "snack_man" },
  { tokenId: 2133, twitter: "digitaldubs" },
  { tokenId: 2147, twitter: "dov_______" },
  { tokenId: 2150, twitter: "MadtownJedi" },
  { tokenId: 2155, twitter: "snack_man" },
  { tokenId: 2156, twitter: "snack_man" },
  { tokenId: 2163, twitter: "snack_man" },
  { tokenId: 2164, twitter: "snack_man" },
  { tokenId: 2165, twitter: "snack_man" },
  { tokenId: 2166, twitter: "snack_man" },
  { tokenId: 2168, twitter: "snack_man" },
  { tokenId: 2169, twitter: "brain_pasta" },
  { tokenId: 2183, twitter: "louiepecan" },
  { tokenId: 2257, twitter: "W3Hidayath" },
  { tokenId: 2261, twitter: "tarisde_nft" },
  { tokenId: 2317, twitter: "ETHtoad" },
  { tokenId: 2530, twitter: "RoseCityWeb3" },
  { tokenId: 2647, twitter: "ArtofOrb" },
];

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== "GET") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  // Try to filter out recently-tweeted pizzas (graceful degradation if KV unavailable)
  let recentTokenIds = new Set<number>();
  try {
    const entries: RecentEntry[] | null = await kv.get<RecentEntry[]>(KV_KEY);
    if (entries) {
      const cutoff = Date.now() - THIRTY_DAYS_MS;
      for (const e of entries) {
        if (new Date(e.tweetedAt).getTime() > cutoff) {
          recentTokenIds.add(e.tokenId);
        }
      }
    }
  } catch {
    // KV not configured — proceed without filtering
  }

  let pool = X_LINKED_PIZZAS.filter((p) => !recentTokenIds.has(p.tokenId));
  // If all are filtered out, fall back to the full list
  if (pool.length === 0) {
    pool = X_LINKED_PIZZAS;
  }

  const entry = pool[Math.floor(Math.random() * pool.length)];

  res.setHeader("Cache-Control", "public, s-maxage=0");
  return res.status(200).json({
    tokenId: entry.tokenId,
    twitter: entry.twitter,
  });
}
